### ISSUE TITLE
Can use examples with python 2.6??

### ISSUE THREAD

**Issue by astrung** [mila-udem/blocks-examples#53]
In installation documentation, i see that block has supported for python 2.6>>But when i run examples for python 2.6,i get this error:
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 104, in _run_module_as_main
    loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib64/python2.6/runpy.py", line 79, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib64/python2.6/pkgutil.py", line 456, in get_loader
    return find_loader(fullname)
  File "/usr/lib64/python2.6/pkgutil.py", line 466, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib64/python2.6/pkgutil.py", line 422, in iter_importers
    __import__(pkg)
  File "sqrt/__init__.py", line 6, in <module>
    from blocks.algorithms import GradientDescent, Scale
  File "/usr/lib/python2.6/site-packages/blocks/algorithms/__init__.py", line 14, in <module>
    from blocks.graph import ComputationGraph
  File "/usr/lib/python2.6/site-packages/blocks/graph.py", line 158
    return {var.name: var for var in self.inputs}
                            ^
SyntaxError: invalid syntax
So i need a new version for python,or i need change code?Or some other ways

**Comment by dmitriy-serdyuk** [comment]
We support and test blocks only with Python 2.7 and 3.4. Update your python installation.

**Comment by dwf** [comment]
https://github.com/mila-udem/blocks/issues/902
