### ISSUE TITLE
decoder.generate is breaking

### ISSUE THREAD

**Issue by sanjeevkrn** [mila-udem/blocks-examples#73]
Hello Guys,

I am trying to understand machine translation example by parts of code over the terminal. However I am stuck with below strange error while generating sequence through decode.generate(). 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/compile/function.py", line 308, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/compile/pfunc.py", line 536, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/compile/function_module.py", line 1766, in orig_function
    output_keys=output_keys).create(
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/compile/function_module.py", line 1422, in __init__
    accept_inplace)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/compile/function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/gof/fg.py", line 171, in __init__
    self.__import_r__(output, reason="init")
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/gof/fg.py", line 315, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/gof/fg.py", line 420, in __import__
    detailed_err_msg)
theano.gof.fg.MissingInputError: A variable that is an input to the graph was neither provided as an input to the function nor given a value. A chain of variables leading from this input to an output is [sequencegenerator_initial_states_states[t-1], sequencegenerator_generate_states, readout_readout_states, merge_apply_states, merge_apply_states, transform_states_apply_input_, dot.0, transform_states_apply_output, merge_apply_states, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, merge_apply_output, initializablefeedforwardsequence_apply_args_0, maxout_bias_apply_input_, Elemwise{add,no_inplace}.0, maxout_bias_apply_output, maxout_apply_input_, Reshape{3}.0, max, maxout_apply_output, softmax0_apply_input_, dot.0, softmax0_apply_output, softmax1_apply_input_, dot.0, Elemwise{add,no_inplace}.0, softmax1_apply_output, initializablefeedforwardsequence_apply_output, readout_readout_output_0, readout_emit_readouts, softmaxemitter_emit_readouts, softmaxemitter_probs_readouts, ndimensionalsoftmax_apply_args_0, ndimensionalsoftmax_apply_input_, Softmax.0, ndimensionalsoftmax_apply_output, ndimensionalsoftmax_apply_output, softmaxemitter_probs_output_0, Reshape{2}.0, Subtensor{::, int64}.0, Shape.0, Elemwise{Cast{int32}}.0, mrg_uniform{TensorType(float64, vector),no_inplace}.0]. This chain may not be unique
Backtrace when the variable is created:
  File "/home/karn_s/.local/lib/python2.7/site-packages/blocks/bricks/recurrent.py", line 230, in recurrent_apply
    brick.name, application.application_name))

The error appears while running following piece of codes:

from model import BidirectionalEncoder
from model import Decoder
import configurations
config = getattr(configurations,'get_config_cs2en')()

source_sentence = tensor.lmatrix('source')
source_sentence_mask = tensor.matrix('source_mask')
encoder = BidirectionalEncoder(config['src_vocab_size'], config['enc_embed'], config['enc_nhids'])
decoder = Decoder(config['trg_vocab_size'], config['dec_embed'], config['dec_nhids'], config['enc_nhids'] * 2)
target_sentence = tensor.lmatrix('target')
target_sentence_mask = tensor.matrix('target_mask')
cost = decoder.cost(encoder.apply(source_sentence, source_sentence_mask), source_sentence_mask, target_sentence, target_sentence_mask)
cst_fn = theano.function([source_sentence,source_sentence_mask,target_sentence,target_sentence_mask],cost)

representation = encoder.apply(source_sentence,source_sentence_mask)
generated = decoder.generate(source_sentence, representation)
generate_fn = theano.function([source_sentence,source_sentence_mask], generated)
<<<<< MissingInputError>>>>>

sampling_input = tensor.lmatrix('input')
sampling_representation = encoder.apply(sampling_input, tensor.ones(sampling_input.shape))
generated = decoder.generate(sampling_input, sampling_representation)
generate_fn = theano.function([sampling_input],generated)
<<<<< MissingInputError>>>>>

Please assist.

**Comment by sanjeevkrn** [comment]
figured it out, forgot to collect updates.
