### ISSUE TITLE
MT example - error in validation in bleu script

### ISSUE THREAD

**Issue by ohadzad** [mila-udem/blocks-examples#86]
When running the bleu evaluation after 80000 runs, it crashes.
please don't mind the row numbers on main and init as I have changed them a bit.
you can reproduce the error if you set the bleu_val_freq to something relatively low (default is 80k).

ERROR:blocks.main_loop:Error occured during training.

Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "machine_translation/__main__.py", line 41, in <module>
    get_dev_stream(**configuration), args.bokeh)
  File "machine_translation/__init__.py", line 175, in main
    main_loop.run()
  File "venv/local/lib/python2.7/site-packages/blocks/main_loop.py", line 197, in run
    reraise_as(e)
  File "venv/local/lib/python2.7/site-packages/blocks/utils/__init__.py", line 258, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "venv/local/lib/python2.7/site-packages/blocks/main_loop.py", line 183, in run
    while self._run_epoch():
  File "venv/local/lib/python2.7/site-packages/blocks/main_loop.py", line 232, in _run_epoch
    while self._run_iteration():
  File "venv/local/lib/python2.7/site-packages/blocks/main_loop.py", line 255, in _run_iteration
    self._run_extensions('after_batch', batch)
  File "venv/local/lib/python2.7/site-packages/blocks/main_loop.py", line 263, in _run_extensions
    extension.dispatch(CallbackName(method_name), *args)
  File "venv/local/lib/python2.7/site-packages/blocks/extensions/__init__.py", line 338, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "machine_translation/sampling.py", line 174, in do
    self._save_model(self._evaluate_model())
  File "machine_translation/sampling.py", line 206, in _evaluate_model
    ignore_first_eol=True)
  File "venv/local/lib/python2.7/site-packages/blocks/search.py", line 266, in search
    self.compile()
  File "venv/local/lib/python2.7/site-packages/blocks/search.py", line 130, in compile
    self._compile_next_state_computer()
  File "venv/local/lib/python2.7/site-packages/blocks/search.py", line 113, in _compile_next_state_computer
    self.contexts + self.input_states + next_outputs, next_states)
  File "venv/local/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1415, in __init__
    self._check_unused_inputs(inputs, outputs, on_unused_input)
  File "venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1553, in _check_unused_inputs
    i.variable, err_msg))
theano.compile.function_module.UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 3 is not part of the computational graph needed to compute the outputs: sequencegenerator_generate_outputs.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.

Original exception:
	UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 3 is not part of the computational graph needed to compute the outputs: sequencegenerator_generate_outputs.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.
Use of uninitialized value $length_reference in numeric eq (==) at ./data/multi-bleu.perl line 148.

**Comment by tnq177** [comment]
I'm facing similar problem.

**Comment by orhanf** [comment]
Might that be related you guys do not add `on_unused_input='warn'` to your `THEANO_FLAGS` ?

**Comment by tnq177** [comment]
@orhanf Thanks a lot. And sorry for not reading the other issues. I've added that into ```THEANO_FLAGS``` and everything is fine now.

**Comment by rizar** [comment]
Thank you @orhanf  for answering, I am closing the issue.

**Comment by ohadzad** [comment]
Thanks @orhanf
