### ISSUE TITLE
gpu out of memory

### ISSUE THREAD

**Issue by luoyangen** [mila-udem/blocks-examples#98]
I just ran the example NMT, the data used was automatic downloaded by prepare_data.py
while using gpu(GTX 850M, 2G gpu mem),
only after 5 iterations, then ran out of memory.
So i'm wandering, how many gpu mem we should have to train the model,
  or did I have some mistakes.

**Comment by nouiz** [comment]
What nvidia-smi tell you? Maybe the GUI take too much ram. From memory 2G
was enough for the examples.

**Comment by orhanf** [comment]
2G might not be enough for the NMT example when vocabulary size is large. 
@luoyangen can you try with smaller vocabulary, batch size and number of hidden units ?

**Comment by nouiz** [comment]
Sorry, I taught this comment where on another repository!

I don't know about the size requirement of this examples.

**Comment by luoyangen** [comment]
Yeah, the reason is memory not enough, After I decreased the hidden layer of both encoder and decoder to 800, and the word embedding to 500, It won't throw that error.
Thanks, @nouiz @orhanf

**Comment by andybug912** [comment]
@luoyangen  hi, could you tell me how to run the code on GPU? I tried `THEANO_FLAGS=device=gpu,floatX=float32 python __main__.py`
kept receiving error  

> TypeError: ('Bad input argument to theano function with name "/nfs/disk/work/users/zhangandy/.local/lib/python2.7/site-packages/blocks/algorithms/**init**.py:254"  at index 0(0-based)', 'TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function".

then I am not sure what should I do next to fix this problem

thanks!

**Comment by nouiz** [comment]
Your dataset is in float64. Make sure to cast it to floatX.

**Comment by andybug912** [comment]
sorry for replying so late

could you explain more in detail? I'm new both in python and theano

**Comment by andybug912** [comment]
@nouiz I added 
`masked_stream = Cast(data_stream=masked_stream,
             dtype='floatX')`
`dev_stream = Cast(data_stream=dev_stream,
             dtype='floatX')`

just before functions return `masked_stream` and `dev_stream` in `stream.py`, and received error

> Traceback (most recent call last):
>   File "**main**.py", line 41, in <module>
>     get_dev_stream(**configuration), args.bokeh)
>   File "/work3/zhangandy/machine_translation/**init**.py", line 145, in main
>     every_n_batches=config['bleu_val_freq']))
>   File "/work3/zhangandy/machine_translation/sampling.py", line 136, in **init**
>     self.vocab = data_stream.dataset.dictionary
> AttributeError: 'Cast' object has no attribute 'dataset'

so I think I may cast the data in a wrong way. Could you tell me how to fix it to run on gpu?
Thanks!
